STOP_WORDS = {
    "ja", "ty", "on", "ona", "ono", "my", "wy", "oni", "one", "mnie", "mi", "mną", "ciebie", "cię", "ci",
    "tobą", "jego", "niego", "go", "jemu", "niemu", "mu", "nim", "jej", "niej", "nią", "nas", "nam", "nami",
    "was", "wam", "wami", "ich", "nich", "im", "nimi", "siebie", "się", "sobie", "sobą", "mój", "moja", "moje",
    "twój", "twoja", "twoje", "nasz", "nasza", "nasze", "wasz", "wasza", "wasze", "swój", "swoja", "swoje",
    "ten", "ta", "to", "tamten", "tamta", "tamto", "taki", "taka", "takie", "tym", "obie", "oba", "oboje",
    "kto", "co", "jaki", "który", "ktoś", "coś", "jakiś", "nikt", "nic", "żaden", "każdy", "wszyscy", "wielu",
    "w", "we", "z", "ze", "na", "do", "dla", "o", "od", "po", "pod", "pode", "nad", "nade", "przed", "przede",
    "za", "przy", "bez", "beze", "u", "ku", "mimo", "pomimo", "wokół", "obok", "wzdłuż", "oprócz", "zamiast",
    "według", "wobec", "pomiędzy", "między", "wewnątrz", "zewnątrz", "poniżej", "powyżej",
    "i", "a", "oraz", "lub", "czy", "albo", "bądź", "ani", "ni", "ale", "lecz", "jednak", "jednakże",
    "zaś", "natomiast", "więc", "dlatego", "zatem", "toteż", "że", "iż", "ponieważ", "bo", "gdy", "gdyby",
    "jeśli", "jeżeli", "choć", "chociaż", "chociażby", "zanim", "aż", "nie", "tak", "niech", "by", "no",
    "oby", "tylko", "nawet", "też", "także", "ponadto", "stąd", "wreszcie", "następnie", "obecnie", "aktualnie",
    "być", "jest", "są", "był", "była", "było", "byli", "były", "będzie", "będą", "będę", "będziesz",
    "mieć", "ma", "mają", "miał", "miała", "miało", "mieli", "miały", "mam", "masz",
    "może", "mogą", "mógł", "mogła", "musieć", "musi", "muszą", "chcieć", "chce", "chcą",
    "został", "została", "zostali", "zostały", "zostać", "powinien", "powinna", "powinno", "powinni",
    "nierzetelnie", "niezwłocznie", "szybko", "wolno", "bardzo", "mało", "dużo", "wiele", "nieco", "zbyt",
    "pan", "pana", "panu", "panem", "pani", "panią", "państwo", "państwa", "państwu", "proszę", "dziękuję",
    "witam", "pozdrawiam", "szanowny", "szanowna", "szanowni", "poważaniem", "poważanie",
    "dnia", "roku", "miesiąca", "ulica", "numer", "telefon", "faks", "email", "mail", "adres",
    "miasto", "miejscowość", "kod", "pocztowy", "nip", "pesel", "regon", "iban", "krs", "cvv", "cvc", "bdo",
    "dowód", "osobisty", "paszport", "załącznik", "dokument", "umowa", "faktura", "paragon", "rachunek",
    "kwota", "suma", "cena", "netto", "brutto", "podatek", "vat", "pit", "cit", "data", "podpis", "pieczęć",
    "sztuka", "uwaga", "strona", "konto", "karta", "kredytowa", "debetowa", "bank", "przelew", "gotówka",
    "imię", "nazwisko", "dane", "osoba", "excel", "dz", "chaos", "wartość", "koszt", "przychód", "dochód",
    "marszałek", "marszałka", "marszałkowi", "marszałkiem", "marszałkowskiego",
    "konserwator", "konserwatora", "konserwatorem",
    "inżynier", "inżyniera", "inżynierem", "dyrektor", "dyrektora", "dyrektorze", "dyrekcja", "główny", "głównego",
    "kierownik", "kierownika", "prezes", "prezesa", "wiceprezes", "członek", "zastępca", "pełnomocnik",
    "wójt", "burmistrz", "starosta", "wojewoda", "poseł", "senator", "sędzia", "prokurator", "adwokat", "radca",
    "delegatura", "delegatury", "zarządzenie", "zarządzenia", "uchwała", "uchwały", "ustawa", "ustawy",
    "wieloletniej", "prognozie", "finansowej", "rozporządzenie", "decyzja", "postanowienie", "zaświadczenie",
    "firma", "spółka", "spółki", "spółką", "przedsiębiorstwo", "działalność", "gospodarcza",
    "urząd", "urzędu", "urzędzie", "urzędem", "gmina", "powiat", "powiatowy",
    "wydział", "wydziału", "departament", "departamentu", "departamencie", "referat", "sekcja",
    "ministerstwo", "ministerstwa", "minister", "ministra", "ministrem", "ministrowi",
    "komisja", "komisji", "komisję", "związek", "związku", "związkiem", "rada", "zarząd",
    "teatr", "teatru", "teatrowi", "teatrem", "teatrze", "muzeum", "szkoła", "uczelnia", "szpital", "przychodnia",
    "województwo", "województwa", "województw", "wojewódzkiego", "wojewódzkiej", "sejmik", "sejmiku",
    "sąd", "sądu", "sądzie", "trybunał", "prokuratura", "policja", "straż",
    "kielce", "kielcach", "kielcami", "kielc", "kieleckich", "kieleckiej", "kiele", "kie",
    "warszawa", "warszawie", "łódź", "łodzi", "częstochowa", "częstochowy", "kraków", "krakowie",
    "poznań", "poznaniu", "wrocław", "wrocławiu", "gdańsk", "gdańsku", "szczecin", "szczecinie",
    "bydgoszcz", "bydgoszczy", "lublin", "lublinie", "katowice", "katowicach", "białystok", "białymstoku",
    "gdynia", "sopot", "rzeszów", "rzeszowie", "toruń", "toruniu", "opole", "opolu",
    "europa", "europie", "islandia", "islandii", "islandzką", "norwegia", "norwegii", "ukraina", "ukrainę", "ue",
    "ul", "al", "pl", "nr", "tel", "fax", "kom", "km", "cm", "mm", "kg", "szt", "egz", "kpl",
    "godz", "min", "sek", "sp", "zoo", "sa", "prof", "dr", "mgr", "inż", "lek", "med", "hab",
    "np", "tj", "tzw", "ww", "itd", "itp", "cdn", "str", "poz", "ust", "art", "par", "pkt",
    "im", "ce", "cach", "ręb", "krzy", "święt", "ill", "nro", "uzp", "inw", "ke",
    "ii", "iii", "iv", "vi", "vii", "viii", "ix", "xi", "xii", "xiii", "xiv", "xv",
    "polska", "polskiej", "polskich", "polską", "polski", "polskie",
    "rzeczypospolita", "rzeczypospolitej", "unijny", "unijna", "unijne", "unijnych",
    "europejski", "europejska", "europejskie", "europejskiego", "krajowy", "krajowa", "krajowe",
    "poprawa", "stan", "zasady", "prawna", "łącza", "łączna", "konieczne", "ośmiomiesięcznego",
    "mucha", "zima", "lato", "wiosna", "jesień", "kowal", "kruk", "lis", "wilk", "niedziela", "sobota",
    "zając", "niedźwiedź", "sowa", "dudek", "kaczka", "gęś", "ptak", "ryba", "kot", "pies",
    "cebula", "burak", "kapusta", "marchew", "woda", "piwo", "wino", "chleb", "masło", "ser",
    "wiatr", "mróz", "burza", "chmura", "słońce", "księżyc", "gwiazda", "niebo", "ziemia",
    "biały", "czarny", "czerwony", "zielony", "niebieski", "żółty", "szary", "brązowy", "złoty", "srebrny",
    "mały", "duży", "gruby", "chudy", "wysoki", "niski", "stary", "nowy", "młody",
    "dobry", "zły", "prawy", "lewy", "góra", "dół", "przód", "tył", "bok", "środek",
    "koniec", "początek", "wielki", "krótki", "długi", "las", "pole", "morze", "rzeka", "góry",
    "dzisiaj", "jutro", "wczoraj", "rano", "wieczór", "południe", "kwartał", "półrocze", "termin", "okres",
}